### ISSUE TITLE
how to use to record uiview

### ISSUE THREAD

**Issue by ashish5016** [davidisaaclee/ViewRecorder#1]
can't understand how to use function...

**Comment by davidisaaclee** [comment]
sorry I didn't see this – this is pretty old code, so I don't remember (and it may not work in latest iOS / Swift). but there seems to be a full example in the repo here: https://github.com/davidisaaclee/ViewRecorder/blob/master/ViewRecorder/ViewController.swift

the important lines seem to be:

1. create a `RecordingContextImpl`, passing the UIView you want to record:

https://github.com/davidisaaclee/ViewRecorder/blob/c2422158b93c6615959f8f1d7df4d76a14d05746/ViewRecorder/ViewController.swift#L22

2. Call `resumeRecording` or `pauseRecording` to record: 

https://github.com/davidisaaclee/ViewRecorder/blob/c2422158b93c6615959f8f1d7df4d76a14d05746/ViewRecorder/ViewController.swift#L41-L47

3. Export the recording to a file using `recorder.exportRecording()`:

https://github.com/davidisaaclee/ViewRecorder/blob/c2422158b93c6615959f8f1d7df4d76a14d05746/ViewRecorder/ViewController.swift#L50-L54

sorry if this is more confusing than it should be – I didn't think about other people using this library, but you are free to do so. 

I know that Apple has made ReplayKit more powerful since I wrote this code – I would look at that and related first-party code to see if there is a better facility for what you are trying to do. https://developer.apple.com/documentation/replaykit

**Comment by davidisaaclee** [comment]
feel free to reopen if this is still an issue
